# Generated by Django 5.1.4 on 2026-04-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar_alter_user_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/'),
        ),
    ]
